server:
  port: 9001
  
#
spring:
  application:
    name: config-client
    # BusProperties
    bus:
      destination: bus-q
      trace:
        enabled: true
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                publisher-confirms: true
      bindings:
        myInput:
          binder: rabbit1
          destination: things1
        myOutput:
          binder: rabbit1
          destination: things1
        # 添加 bus 绑定 通道配置
        springCloudBusInput:
          binder: rabbit1
        springCloudBusOutput:
          binder: rabbit1
 
# actuator
#http://localhost:9001/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 打印log日志
logging:
  level:
    root: warn
    org.springframework.cloud: debug 

#自定义属性
name: '{cipher}85618eb7273fce6edee8b017b58f7247281fffe35f48f8eceb100d2c0323a51d'
age: 33
password: 123456