server:
  port: 9002
  
#
spring:
  application:
    name: config-client
  cloud:
    config:
      discovery:
        enabled: true
    # BusProperties
    bus:
      destination: bus-q
      trace:
        enabled: true
      id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
    stream:
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                publisher-confirms: true
      bindings:
        myInput:
          binder: rabbit1
          destination: things1
        myOutput:
          binder: rabbit1
          destination: things1
        # 添加 bus 绑定 通道配置
        springCloudBusInput:
          binder: rabbit1
        springCloudBusOutput:
          binder: rabbit1
 
# actuator
#http://localhost:9001/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

## eureka
##如果用服务id去进行访问，
##那么请求地址用http:网关地址/serviceId/具体的url
eureka:
  client:
    enabled: true
    service-url: # http://localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  
# 打印log日志
logging:
  level:
    root: warn
    org.springframework.cloud: debug
